### ISSUE TITLE
Request: a version for windows

### ISSUE THREAD

**Issue by justa9** [myint/cronometer#1]
Hello.

Could there be a version for windows (win32)?

Thanks.

**Comment by myint** [comment]
This repository is a fork of the original Cronometer. The main changes I made were to improve OS X integration and update the USDA database.

You can download the original, which has Windows support:

https://cronometer.com/download/

**Comment by justa9** [comment]
Thank you very much for the clarification. Although an updated version of the windows program with the latest USDA database would be appreciated, I understand that this is not the scope of this repo.
